#!/bin/sh
exec 2>&1
if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

exec /nix/var/nix/profiles/default/bin/nix-daemon
