:em: {sp}--{sp}
:license: GNU Affero General Public License version 3.0 or later
:license-link: link:https://www.gnu.org/licenses/agpl-3.0.en.html[]
:raw-url: https://raw.githubusercontent.com/vs-123/kalium-void/refs/heads/main

= KALIUM VOID

*Kalium Void* is my own personal spin-off of Void Linux. 

== HOW TO INSTALL

Assuming you've booted into the live ISO, you may install Kalium Void in one of two ways {em} <<installer-method,GUIDED METHOD>> or <<manual-method,MANUAL METHOD>>

[[installer-method]]
=== GUIDED METHOD

An installer script `kalium-installer.sh` is provided at `~/scripts/kalium-installer.sh`. You may execute `kalium-installer.sh` directly as an administrator and follow the on-screen instructions.

[source,shell]
----
sudo ~/scripts/kalium-installer.sh
----

[[manual-method]]
=== MANUAL METHOD

* Make disk and format and mount

[source,shell]
----
cfdisk
# /dev/sda1   1G  (EFI)
# /dev/sda2   12G (SWAP)
# /dev/sda3   1G  (ROOT PARTITION)

mkfs.vfat /dev/sda1
mkfs.ext4 /dev/sda3
mkswap    /dev/sda2

mount --mkdir /dev/sda3 /mnt
mount --mkdir /dev/sda1 /mnt/boot/efi
swapon /dev/sda2
----

* Instead of manually installing packages, clone the live session

[source,shell]
----
sudo rsync -axHAWXS --numeric-ids --info=progress2 / /mnt

# `-x` -- STAY ON ONE FILE SYSTEM 
#         (DON'T TRY TO COPY `/DEV` OR `/PROC` VIRTUAL FILES).
#
# `-aHAWXS` -- PRESERVES EVERYTHING SUCH AS 
#              PERMISSIONS, HARD LINKS, SYMLINKS 
#              AND EXTENDED ATTRIBUTES.
----


* Generate fstab

[source,shell]
----
xgenfstab -U /mnt > outputs.txt
# open outputs.txt in an editor, copy its content 
# and *append* it to /mnt/etc/fstab

# OR

xgenfstab -U /mnt >> /mnt/etc/fstab
----

* Mount these `/dev` `/sys` `/proc`

[source,shell]
----
mount --rbind /dev /mnt/dev
mount --rbind /sys /mnt/sys
mount --rbind /proc /mnt/proc

# OR

for i in dev sys proc; do; mount --rbind /$i /mnt/$i; done
----

* `chroot` and setup stuff

[source,shell]
----
chroot /mnt /bin/zsh

# SETUP
passwd   # SET ROOT PASSWORD
useradd -m -G wheel,audio,video,storage,users USER_NAME   # ADD NEW USER `USER_NAME`
passwd USER_NAME

# INSTALL GRUB
grub-install --target=arm64-efi --efi-directory=/boot/efi --bootloader-id="Kalium Void"

xbps-reconfigure -fa

# SANITY CHECK FOR GRUB
ls /boot/grub/
grep menuentry /boot/grub/grub.cfg
----

* Exit `chroot`

[source,shell]
----
exit
umount -R /mnt
----

* Poweroff, eject the ISO and boot up.

* *THE END*

== LICENSE

This project is licensed under the *{license}*.

*NO WARRANTY PROVIDED*

For more information, see `LICENSE` file or visit {license-link}.
