vim.g.mapleader = " "

vim.keymap.set('c', '<C-a>', '<HOME>', { silent = true })
vim.keymap.set('c', '<C-e>', '<END>', { silent = true })
vim.keymap.set('n', '<C-w>1', ':on<CR>', { silent = true })
vim.keymap.set('n', 'gf', ':Fluoride<CR>', { silent = true })
vim.keymap.set('n', '<leader>e', ':Ex<CR>', { silent = true })
vim.keymap.set('n', '<leader>h', ':bp<CR>', { silent = true })
vim.keymap.set('n', '<leader>l', ':bn<CR>', { silent = true })
vim.keymap.set('n', '<leader>q', ':bd<CR>', { silent = true })
vim.keymap.set('n', '<leader>q', ':bd<CR>', { silent = true })
vim.keymap.set('n', '<leader>Q', ':bd!<CR>', { silent = true })
vim.keymap.set('n', '<leader>t', ':term<CR>', { silent = true })
vim.keymap.set('t', '<esc>', '<C-\\><C-n>', { silent = true })

vim.keymap.set('n', '<leader>f', function()
   vim.lsp.buf.format({ async = true })
   print("[LSP] FORMAT")
end)

vim.keymap.set('n', '<leader>r', function()
   vim.ui.input({ prompt = '[RENAME] ' }, function(inp)
      vim.lsp.buf.rename(inp)
      print("[LSP] RENAME")
   end)
end)

vim.keymap.set('n', '<leader>j', function()
   vim.lsp.buf.definition()
   print("[LSP] DEFINITION")
end)

vim.keymap.set('n', '<leader>R', function()
   vim.lsp.buf.references()
   print("[LSP] REFERENCES")
end)
