name: BUILD KALIUM VOID ISO

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-aarch64:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: CHECKOUT KALIUM-VOID REPO
        uses: actions/checkout@v4

      - name: CHECKOUT KALIUM-REPO REPO
        uses: actions/checkout@v4
        with:
          repository: vs-123/kalium-repo
          path: kalium-repo

      - name: BUILD INSIDE DOCKER
        run: |
          docker run --privileged --rm \
            -v $(pwd):/work \
            -w /work \
            ghcr.io/void-linux/void-linux:latest-full-aarch64 \
            /bin/bash -c "
              xbps-install -Sy wget git xz lz4 qemu-user-static-binfmt binfmt-support

              cd kalium-repo
              ./xbps-src binary-bootstrap
              ./xbps-src pkg kalium-base-files
              ./xbps-src pkg kalium-base-systems
              xbps-rindex -a hostdir/binpkgs/*.xbps
              cd ..

              git clone --depth 1 https://github.com/void-linux/void-mklive.git
              sed -i 's/umount -R -f/umount -l -R -f/g' ./void-mklive/mklive.sh
              
              bash ./build.sh aarch64
            "

      - name: GENERATE CHECKSUM & RENAME
        run: |
          TAG_NAME="${{ github.ref_name }}"
          shasum -a 256 kalium-void-aarch64.iso > kalium-void-aarch64-sha256sum.txt
          mv kalium-void-aarch64.iso "kalium-void-aarch64-${TAG_NAME}.iso"

      - name: CREATE RELEASE AND UPLOAD ASSET
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kalium-void-aarch64*.iso
            *sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
