name: BUILD KALIUM VOID ISO

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged 

    steps:
      - name: INSTALL HOST DEPENDENCIES
        run: |
          xbps-install -Sy git base-devel liblz4 xz qemu-user-static

      - name: CHECKOUT REPOS
        run: |
          git clone --depth 1 https://github.com/vs-123/kalium-repo.git
          git clone --depth 1 https://github.com/void-linux/void-mklive.git

      - name: BUILD CUSTOM PACKAGES (Cross-compile to aarch64)
        working-directory: kalium-repo
        run: |
          echo "XBPS_CHROOT_CMD=eth" >> etc/conf
          ./xbps-src binary-bootstrap
          ./xbps-src -a aarch64 pkg kalium-base-files
          ./xbps-src -a aarch64 pkg kalium-base-system
          
          xbps-rindex -a hostdir/binpkgs/kalium-base-*.xbps

      - name: BUILD ISO
        working-directory: void-mklive
        run: |
          ARCH=$1
          
          if [ ! -d "void-mklive" ]
          then
          	git clone --depth 1 https://github.com/void-linux/void-mklive.git
          fi
          
          cd ./void-mklive 
          
          rm ./data/splash.png &&
          rm ./data/issue &&
          cp ../splash.png ./data/ &&
          mkdir -p ../kalium-iso-overlay/usr/share/ &&
          cp ../splash.png ../kalium-iso-overlay/usr/share/splash.png &&
          cp ../kalium-iso-overlay/etc/issue ./data/issue
          
          yes | sudo ./mklive.sh \
          	-a $ARCH \
          	-p "$(cat ../packages.txt)"  \
          	-r ./kalium-repo/hostdir/binpkgs \
          	-S "acpid dhcpcd sshd"  \
          	-I ../kalium-iso-overlay \
          	-x ../finish_kalium_void.sh  \
          	-T "Kalium Void" \
          	-e /bin/zsh \
          	-r "https://github.com/index-0/librewolf-void/releases/latest/download/" \
          	-o "../kalium-void-$ARCH.iso"

      - name: UPLOAD
        uses: actions/upload-artifact@v4
        with:
          name: kalium-void-iso
          path: void-mklive/*.iso
